export const types = {
  ghost: 'Ghost',
  bug: 'Bug',
  ground: 'Ground',
  rock: 'Rock',
  steel: 'Steel',
  fairy: 'Fairy',
  dark: 'Dark',
  fire: 'Fire',
  water: 'Water',
  psychic: 'Psychic',
  ice: 'Ice',
  poison: 'Poison',
  dragon: 'Dragon',
  grass: 'Grass',
  flying: 'Flying',
  fight: 'Fight',
  electric: 'Electric',
  normal: 'Normal'
}
